package com.bek.ticketService;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;

@Getter
@Setter
public class User {
    private String name;
    private int id;//generated by id, then set to id by setter/ later I can use that to create new ticket
    private final LocalDate startDate = LocalDate.now();

    public User(String name) {
        this.name = name;
    }

    public void getTicket(Ticket.TicketType type, Ticket.TicketClass clazz) {
        Ticket newTicket = new Ticket(type, clazz);

        System.out.println("You bought a ticket for: " + clazz + ", for " + type);
    }

}
